### ISSUE TITLE
mutually exclusive parameters

### ISSUE THREAD

**Issue by luto** [Uberspace/paternoster#16]
Add mutually exclusive parameters (e.g. `--debug` and `--quiet`). 

```yml
- hosts: paternoster
  vars:
    description: Do something
    parameters:
      - name: debug
        short: d
        action: store_true
      - name: quiet
        short: q
        action: store_true
    mutually_exclusive:
      - - debug
        - quiet
```

(just like ansible http://mobygeek.net/blog/2016/02/16/ansible-module-development-parameters/)
