### ISSUE TITLE
add "one of group must be given" arguments

### ISSUE THREAD

**Issue by luto** [Uberspace/paternoster#19]
Add argument groups of which at least one must be given (e.g. `--webserver` or `--mailserver` when adding a domain).

```yml
- hosts: paternoster
  vars:
    description: Do something
    parameters:
      - name: webserver
        short: d
        action: store_true
      - name: mailserver
        short: q
        action: store_true
    required_one_of:
      - - webserver
        - mailserver
```

(just like ansible http://mobygeek.net/blog/2016/02/16/ansible-module-development-parameters/)
