### ISSUE TITLE
Fix error output when using `fail` or `assert` within a loop

### ISSUE THREAD

**Issue by luto** [Uberspace/paternoster#2]
The following ansible task generates only the error message "One or more items failed", instead of the one supplied in `msg`.

```yaml
- assert:
    that: item < 3
    msg: "your value uses too many bits!"
  with_items: [0, 1, 5, 2]
```

Investigate the reason for this behavior and fix it, if possible.
