### ISSUE TITLE
mutually_exclusive does not work with boolean flags

### ISSUE THREAD

**Issue by luto** [Uberspace/paternoster#24]
```yml
#!/usr/bin/env paternoster

- hosts: paternoster
  vars:
    parameters:
      - name: static
        action: store_true
        dest: transport
      - name: tcp
        action: store_true
        dest: transport
    mutually_exclusive:
      - - static
        - tcp
```

When there is a `mutually_exclusive`-group consisting of arguments, which write into the same `dest`, paternoster is no longer able to distinguish between the arguments:

```
[luto@host]$ ./foo.yml --tcp
usage: foo.yml [-h] [--static] [--tcp] [-v]
foo.yml: error: arguments --static, --tcp are mutually exclusive.
[luto@host]$ ./foo.yml --static
usage: foo.yml [-h] [--static] [--tcp] [-v]
foo.yml: error: arguments --static, --tcp are mutually exclusive.
```
