### ISSUE TITLE
no_echo prompt echoes value in error message

### ISSUE THREAD

**Issue by luto** [Uberspace/paternoster#26]
```
- hosts: paternoster
  vars:
    parameters:
      - name: domain
        short: d
        type: paternoster.types.domain
        prompt: yes
        prompt_options:
          confirm: yes
          no_echo: yes
```

```
[root@centos-s-2vcpu-4gb-fra1-01 ~]# ./add-domain 
Domain: (enter "qwe")
Please confirm: (enter "qwe")
usage: add-domain [-h] [-d DOMAIN] [-v]
add-domain: error: argument -d/--domain: invalid domain value: 'qwe'
```
