### ISSUE TITLE
Allow the parameter list to be supplied within the playbook itself

### ISSUE THREAD

**Issue by luto** [Uberspace/paternoster#6]
Currently each paternoster script requires two files - one playbook, which contains the tasks to be executed and one python file, which interfaces with the user. Using a pseudo-play within the playbook as well as a hashbang-line, we should be able to get rid of the python file altogether.

```yaml
#!/usr/bin/paternoster

- hosts: paternoster
  vars:
    parameters:
      - name: domain
        short: d
        help: "the domain name, which should be added (e.g. "google.com")"
        type: paternoster.types.domain(wildcard=True)
      - name: web
        short: w
        help: add domain to the webserver configuration
        action: store_const
        dest: type
        const: web
    success_msg: 'The domain has been added successfully.'
    user:
      name: root
      become: yes

- name: add a domain
  hosts: localhost
  tasks:
    - name: check that the domain is not taken
      assert:
        that: "{{ param_domain not in item.value.domains|default({}) }}"
      register: taken
      ignore_errors: yes
    
    # and so on...
```
